### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by Jeetah** [mrodalgaard/language-log#15]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [language-log](https://github.com/MRodalgaard/language-log) package, v1.4.0

### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:794

Error: This TextEditor has been destroyed
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:794:15)
    at TextEditorMarker.module.exports.TextEditorMarker.getHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:179:33)
    at Cursor.module.exports.Cursor.getScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:73:26)
    at Cursor.module.exports.Cursor.getScreenRange (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:685:20)
    at Cursor.module.exports.Cursor.autoscroll (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:690:51)
    at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:675:21)
    at Cursor.module.exports.Cursor.setBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:80:19)
    at Cursor.module.exports.Cursor.moveToBottom (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:304:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1612:23
    at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1726:9)
    at TextEditor.module.exports.TextEditor.moveToBottom (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1611:19)
    at LogView.module.exports.LogView.tail (/Users/olihd/.atom/packages/language-log/lib/log-view.coffee:167:17)
    at /Users/olihd/.atom/packages/language-log/lib/log-view.coffee:98:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1378:25
```

### Commands

```
     -1:42.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:40.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:39.9.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -1:39.1.0 core:copy (atom-text-editor.editor.is-focused)
     -1:38.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:38.4.0 core:paste (atom-text-editor.editor.is-focused)
  4x -1:34.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:31.7.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:31.3.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -1:29.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
  6x -1:24.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:14.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:27.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:26.3.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:14 core:backspace (atom-text-editor.editor.is-focused)
     -0:12.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "language-log": {
    "tail": true
  }
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v0.6.0
atom-beautify, v0.29.7
atom-commander, v0.7.0
compare-files, v0.6.2
json-colorer, v0.3.0
json-schema, v0.1.15
language-log, v1.4.0
merge-conflicts, v1.4.2
minimap, v4.23.5
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.0
pigments, v0.26.2
project-manager, v2.9.7
tail, v0.1.0

# Dev
No dev packages
```

**Comment by lewismoten** [comment]
I just ran into this bug and was directed here. All packages up to date.

**Comment by mrodalgaard** [comment]
You are right! Forgot to update the package after fixing this. A new package version has been published now.
