### ISSUE TITLE
Uncaught TypeError: target[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by Irthen** [mrodalgaard/language-log#35]
[Enter steps to reproduce:]

1. Open atom.
2. Open a log file which contains something.
3. If I now put the cursor somewhere in the log file, the issue is shown.

**Atom**: 1.23.0-beta0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [language-log](https://github.com/MRodalgaard/language-log) package 1.9.0

### Stack Trace

Uncaught TypeError: target[Symbol.iterator] is not a function

```
At /Applications/Atom.app/Contents/Resources/app/src/tooltip-manager.js:117

TypeError: target[Symbol.iterator] is not a function
    at TooltipManager.add (/Applications/Atom.app/Contents/Resources/app/src/tooltip-manager.js:117:35)
    at LogView.module.exports.LogView.initialize (/packages/language-log/lib/log-view.coffee:71:36)
    at /packages/git-plus/node_modules/space-pen/lib/space-pen.js:184:25)
    at /packages/language-log/lib/log-view.coffee:52:5)
    at Object.addLogPanel (/packages/language-log/lib/main.coffee:65:22)
    at /packages/language-log/lib/main.coffee:58:10
    at TextEditor.observeGrammar (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:727:11)
    at Object.itemUpdate (/packages/language-log/lib/main.coffee:55:33)
    at /packages/language-log/lib/main.coffee:42:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:492:28)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:284:26)
    at PaneContainer.didActivatePane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:262:18)
    at Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:1002:46)
    at Pane.focus (/Applications/Atom.app/Contents/Resources/app/src/pane.js:393:23)
    at /app.asar/src/pane-element.js:51:25)
```

### Commands

```
     -3:04.6.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -3:03.5.0 core:move-down (input.hidden-input)
  2x -3:03.1.0 core:backspace (input.hidden-input)
     -3:02.0 core:save (input.hidden-input)
     -2:23.3.0 core:copy (input.hidden-input)
  2x -2:19.6.0 editor:newline (input.hidden-input)
     -2:17.1.0 autocomplete-plus:confirm (input.hidden-input)
     -2:17.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:16.5.0 core:paste (input.hidden-input)
     -2:16.3.0 editor:consolidate-selections (input.hidden-input)
  3x -2:16 core:move-right (input.hidden-input)
     -2:14.3.0 core:save (input.hidden-input)
     -0:17 core:select-all (input.hidden-input)
     -0:16.4.0 core:backspace (input.hidden-input)
     -0:16.1.0 core:save (input.hidden-input)
     -0:07.4.0 core:cancel (a.stack-toggle)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-bracket-highlight 0.3.2 
atom-clock 0.1.15 
atom-material-syntax 1.0.7 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.6 
chester-atom-syntax 0.3.0 
ctags-status 1.3.7 
dqs-shell-commands 2.2.3 
emmet 2.4.3 
file-icons 2.1.13 
filesize 3.0.0 
flex-tool-bar 0.12.0 
fonts 3.0.3 
git-blame 1.3.1 
git-control 0.9.0 
git-history 3.3.0 
git-log 0.4.1 
git-plus 7.10.0 
git-time-machine 1.5.9 
goto-definition 1.3.4 
highlight-line 0.12.0 
highlight-selected 0.13.1 
hyperclick 0.1.5 
keyboard-scroll 0.7.0 
language-generic-config 1.4.0 
language-log 1.9.0 
language-perl-template-toolkit 0.1.0 
less-than-slash 0.17.0 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-autohider 1.5.3 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-split-diff 0.3.7 
open-files 0.8.2 
open-terminal-here 2.3.1 
pdf-view 0.59.0 
process-palette 0.15.2 
project-manager 3.3.5 
split-diff 1.5.1 
status-bar-blame 2.0.1 
symbols-list 2.4.1 
tab-numbers 0.6.1 
term3 0.22.1 
todo-show 2.1.0 
tool-bar 1.1.0 
tree-view-autoresize 2.2.0 
tree-view-git-status 1.4.0 
```

**Comment by Irthen** [comment]
Issue fixed by https://github.com/atom/atom/pull/16144.
