### ISSUE TITLE
Feature Request: Monolog

### ISSUE THREAD

**Issue by repat** [mrodalgaard/language-log#41]
https://packagist.org/packages/monolog/monolog

~84 Million projects use it, including the biggest frameworks Laravel and Symfony out of the box

**Comment by mrodalgaard** [comment]
Could you add an example log file, thank you.

**Comment by repat** [comment]
Created using [Laravels](https://laravel.com/docs/5.6/logging) `Log`:

```
[2018-03-07 10:49:15] local.EMERGENCY: this is an emergency log  
[2018-03-07 10:49:35] local.ALERT: this is an alert log  
[2018-03-07 10:49:50] local.CRITICAL: this is a critical log  
[2018-03-07 10:46:37] local.ERROR: this is an error log  
[2018-03-07 10:50:03] local.WARNING: this is a warning log  
[2018-03-07 10:50:16] local.NOTICE: this is a notice log  
[2018-03-07 10:46:50] local.DEBUG: this is a debug log with only a string  
[2018-03-07 10:47:18] local.DEBUG: this is a debug log with an optional array {"foo":"bar"} 
[2018-03-07 10:46:30] local.INFO: this is an info log  
[2018-03-06 01:53:27] local.ERROR: This is a real error message with Stacktrace. (View: /Users/user/Documents/GitHub/project/resources/views/layouts/error.blade.php) (View: /Users/user/Documents/GitHub/project/resources/views/layouts/error.blade.php) {"exception":"[object] (ErrorException(code: 0): The Mix manifest does not exist. (View: /Users/user/Documents/GitHub/project/resources/views/layouts/error.blade.php) (View: /Users/user/Documents/GitHub/project/resources/views/layouts/error.blade.php) at /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:586, ErrorException(code: 0): The Mix manifest does not exist. (View: /Users/user/Documents/GitHub/project/resources/views/layouts/error.blade.php) at /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:586, Exception(code: 0): The Mix manifest does not exist. at /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:586)
[stacktrace]
#0 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(45): Illuminate\\View\\Engines\\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/Users/user/Doc...', Array)
#2 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/View/View.php(137): Illuminate\\View\\Engines\\CompilerEngine->get('/Users/user/Doc...', Array)
#3 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/View/View.php(120): Illuminate\\View\\View->getContents()
#4 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/View/View.php(85): Illuminate\\View\\View->renderContents()
#5 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\\View\\View->render()
#6 /Users/user/Documents/GitHub/project/vendor/symfony/http-foundation/Response.php(196): Illuminate\\Http\\Response->setContent(Object(Illuminate\\View\\View))
#7 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(55): Symfony\\Component\\HttpFoundation\\Response->__construct(Object(Illuminate\\View\\View), 404, Array)
#8 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\Routing\\ResponseFactory->make(Object(Illuminate\\View\\View), 404, Array)
#9 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(406): Illuminate\\Routing\\ResponseFactory->view('errors::404', Array, 404, Array)
#10 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(296): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException(Object(Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException))
#11 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(188): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException))
#12 /Users/user/Documents/GitHub/project/app/Exceptions/Handler.php(52): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException))
#13 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(83): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException))
#14 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): Illuminate\\Routing\\Pipeline->handleException(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException))
#15 /Users/user/Documents/GitHub/project/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /Users/user/Documents/GitHub/project/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#35 /Users/user/Documents/GitHub/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#36 /Users/user/Documents/GitHub/project/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#37 /Users/user/.composer/vendor/laravel/valet/server.php(133): require('/Users/user/Doc...')
#38 {main}
"} 
```
follows https://tools.ietf.org/html/rfc5424
